# ---------------------------------------------------------------------------
# medusa engine — Linux build (x64)
#
# Produces five static libraries used by the DarkSpace server build (and
# by anything else that links against medusa on Linux):
#
#   Bin/Linux-x64/<config>/libMedusa[D].a
#   Bin/Linux-x64/<config>/libNetwork[D].a
#   Bin/Linux-x64/<config>/libWorld[D].a
#   Bin/Linux-x64/<config>/libGCQ[D].a
#   Bin/Linux-x64/<config>/libRender3D[D].a
#
# This file replaces the per-project WinGDB-autogenerated makefiles under
# Medusa/, Network/, World/, GCQ/, Render3D/.  Those makefiles' source
# lists had drifted out of sync with disk (missing RenderSnapshot.cpp,
# MaterialComposite.cpp, ChatLog.cpp, ThreadPool.cpp, ...) and referenced
# zlib files that no longer exist.  Source discovery here is glob-based
# so newly-added files are picked up automatically.
#
# Usage:
#   make                    # CONFIG=Release, build all five libs
#   make CONFIG=Debug       # debug variant, libs get D suffix
#   make medusa             # one lib at a time
#   make -j8                # parallel
#   make clean              # nuke obj/ and Bin/Linux-x64/
# ---------------------------------------------------------------------------

CONFIG   ?= Release
PLATFORM := Linux-x64

# Toolchain
CC       := gcc
CXX      := g++
AR       := ar

# Architecture: 64-bit explicit so we're not host-dependent.
ARCH_FLAGS := -m64

# Common include search paths.
# -I.                          medusa root (so `#include "World/RenderSnapshot.h"` works)
# -IThirdParty                 generic ThirdParty headers (re2, zlib, stb, ...)
# -IThirdParty/squish-1.10     DXT compression headers used by Medusa
# -IThirdParty/LuaJIT/src      Lua headers used by World scripting
INC_FLAGS := -I. -IThirdParty -IThirdParty/squish-1.10 -IThirdParty/LuaJIT/src

# Warnings: keep -Wall on but silence the noisy legacy ones so the build
# output stays readable.  Tune as needed once code is cleaned up.
# C-safe warning suppressions (apply to both .c and .cpp builds).
WARN_FLAGS_COMMON := -Wall \
                     -Wno-unused-parameter \
                     -Wno-unused-variable \
                     -Wno-unused-function \
                     -Wno-unused-but-set-variable \
                     -Wno-sign-compare \
                     -Wno-deprecated-declarations \
                     -Wno-write-strings \
                     -Wno-multichar \
                     -Wno-parentheses \
                     -Wno-unknown-pragmas \
                     -Wno-comment \
                     -Wno-misleading-indentation

# C++-only suppressions (gcc warns "valid for C++/ObjC++ but not for C" if
# these are passed when compiling .c files).
WARN_FLAGS_CXX := $(WARN_FLAGS_COMMON) \
                  -Wno-reorder \
                  -Wno-class-memaccess \
                  -Wno-overloaded-virtual

ifeq ($(CONFIG),Debug)
  CFG_FLAGS  := -g -O0 -D_DEBUG
  LIB_SUFFIX := D
else ifeq ($(CONFIG),Release)
  CFG_FLAGS  := -O2 -g -DNDEBUG
  LIB_SUFFIX :=
else
  $(error CONFIG must be Debug or Release (got '$(CONFIG)'))
endif

# ASAN=1 — AddressSanitizer.  Catches heap UB (double-free, UAF, OOB, leaks)
# at the moment of occurrence with full backtraces.  Slows the binary ~2x
# and bloats memory ~3x but tells you EXACTLY where a race-y double-free or
# heap overflow happened.  Pair with the matching ASAN=1 build of darkspace.
# Run with `ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 ./DarkSpaceServer`
# for an immediate stack dump on the first violation.
ifeq ($(ASAN),1)
  CFG_FLAGS += -fsanitize=address -fno-omit-frame-pointer
  ASAN_LDFLAGS := -fsanitize=address
else
  ASAN_LDFLAGS :=
endif

# Z_SOLO: build bundled zlib without its gzfile API (we don't use gzopen
# et al, and gzguts.h is not present in this trimmed zlib drop).
COMMON_FLAGS := $(ARCH_FLAGS) $(CFG_FLAGS) $(INC_FLAGS) \
                -fno-strict-aliasing \
                -fPIC \
                -DZ_SOLO
# Note: -fvisibility=hidden removed.  The server binary dlopens
# libGadgets.so at startup; that shared lib has undefined references to
# engine classes (NounPlanet, GadgetDrive, ...) which need to resolve
# against symbols exported from the server binary.  Default visibility
# + -rdynamic on the server link makes that work.  -fPIC kept on for
# every compile so .o files are usable from both the static server
# binary and the shared libGadgets.so.

CFLAGS   := $(COMMON_FLAGS) $(WARN_FLAGS_COMMON)
CXXFLAGS := $(COMMON_FLAGS) $(WARN_FLAGS_CXX) -std=c++17
ARFLAGS  := rcs

# Output layout (alongside the existing MSBuild Win32/x64 trees under Bin/).
OUT_DIR  := Bin/$(PLATFORM)/$(CONFIG)
OBJ_DIR  := obj/$(PLATFORM)/$(CONFIG)

# ---------------------------------------------------------------------------
# Library source lists
#
# Pattern: $(wildcard <dir>/*.cpp) for first-party dirs (drift-proof —
# adding a new .cpp here works without touching this Makefile).  Explicit
# lists for ThirdParty bits where we need to exclude standalone tools.
# ---------------------------------------------------------------------------

# libMedusa — aggregates code from many medusa subdirs into one core lib.
#
# Scope: only what DarkSpaceServer needs to LINK against (directly or via
# the libs it depends on like Render3D).  Audio/Display/Draw are kept
# because Render3D references their types at the symbol level — dropping
# them would break the server link (vtable + static-member resolution).
# Movie/ is excluded — zero references anywhere in the server path.
#
# If Render3D ever gets refactored to split data-types from render-methods,
# we could further drop Audio/Display/Draw here too.
MEDUSA_DIRS    := Audio Debug Display Draw Factory File Math \
                  Reflection Resource Standard System
MEDUSA_SRC_CPP := $(foreach d,$(MEDUSA_DIRS),$(wildcard $(d)/*.cpp))

# re2 ships timer.c and try.c with their own main() — those are standalone
# test programs, not library code.  Filter them out.
MEDUSA_RE2_C   := $(filter-out ThirdParty/re2/timer.c ThirdParty/re2/try.c, \
                              $(wildcard ThirdParty/re2/*.c))
MEDUSA_ZLIB_C  := $(wildcard ThirdParty/zlib/*.c)
MEDUSA_SRC_C   := $(MEDUSA_RE2_C) $(MEDUSA_ZLIB_C)

MEDUSA_OBJ     := $(MEDUSA_SRC_CPP:%.cpp=$(OBJ_DIR)/%.o) \
                  $(MEDUSA_SRC_C:%.c=$(OBJ_DIR)/%.o)

# Single-dir libs — each one is just $(wildcard <dir>/*.cpp).
#
# MirrorServerDepreciated.cpp and MirrorServerVersionControl.cpp are orphan
# stubs left on disk from a long-removed version-control feature.  They
# define methods that no longer exist on MirrorServer (the header was
# trimmed but the .cpp's weren't deleted).  The legacy WinGDB Makefile
# explicitly excluded them from SOURCES; we do the same here.
NETWORK_SRC    := $(filter-out Network/MirrorServerDepreciated.cpp \
                               Network/MirrorServerVersionControl.cpp, \
                              $(wildcard Network/*.cpp))
NETWORK_OBJ    := $(NETWORK_SRC:%.cpp=$(OBJ_DIR)/%.o)

WORLD_SRC      := $(wildcard World/*.cpp)
WORLD_OBJ      := $(WORLD_SRC:%.cpp=$(OBJ_DIR)/%.o)

# GCQ/ChatLog.cpp uses MSVC stdafx.h precompiled-header style and is not
# in the legacy WinGDB Makefile's source list — orphan, same as the
# MirrorServer pair above.
GCQ_SRC        := $(filter-out GCQ/ChatLog.cpp,$(wildcard GCQ/*.cpp))
GCQ_OBJ        := $(GCQ_SRC:%.cpp=$(OBJ_DIR)/%.o)

# Render3D/MaterialComposite.cpp is an orphan that references an old
# Material / ColorFormat / PrimitiveSurface API (Source factory tag,
# enableColorKey, MIPMAP, findBestAlphaFormat, etc.) that has since been
# removed.  Not in the legacy WinGDB Render3D Makefile either.
RENDER3D_SRC   := $(filter-out Render3D/MaterialComposite.cpp, \
                              $(wildcard Render3D/*.cpp))
RENDER3D_OBJ   := $(RENDER3D_SRC:%.cpp=$(OBJ_DIR)/%.o)

# LuaJIT — same approach as Windows (LuaJIT/src/LuaLib.vcxproj): we compile
# from source rather than linking a prebuilt blob.  The bundled
# ThirdParty/LuaJIT/bin/liblua51.a is x86 and unusable for our x64 build.
# Source list matches LuaLib.vcxproj: every .c in ThirdParty/LuaJIT/src/
# EXCEPT lua.c (the standalone interpreter main) and luac.c (the bytecode
# compiler main) — both ship with their own main() and aren't part of the
# library.  Output is liblua51.a (TargetName=lua51 on Windows, matches the
# legacy `-llua51` link convention).
LUAJIT_DIR     := ThirdParty/LuaJIT/src
# Excluded from the Linux build:
#  - lua.c / luac.c       — standalone interpreter / bytecode-compiler mains
#  - ljit_backend.c, ljit_core.c, ljit_dasm.c, ljit_mem.c — the JIT codegen
#    path.  LuaJIT 1.x JIT is x86-only and depends on DynASM's dasm_proto.h
#    which isn't bundled.  We define USE_PLAIN_LUA below to make the
#    interpreter skip every luaJIT_* entry point, so these .c files become
#    dead weight and we can drop them entirely.  Effect: server runs scripts
#    through the standard Lua 5.1 bytecode interpreter (no JIT) — slower
#    than JIT, fine for game logic / scripted events.
#  - ljitlib.c            — Lua-side `jit.*` API.  Drops with the above; if
#    game scripts ever call jit.on/off/etc. we'd need a stub.  Doesn't seem
#    to be used by DarkSpace scripts in practice.
LUAJIT_EXCLUDE := $(LUAJIT_DIR)/lua.c \
                  $(LUAJIT_DIR)/luac.c \
                  $(LUAJIT_DIR)/ljit_backend.c \
                  $(LUAJIT_DIR)/ljit_core.c \
                  $(LUAJIT_DIR)/ljit_dasm.c \
                  $(LUAJIT_DIR)/ljit_mem.c \
                  $(LUAJIT_DIR)/ljitlib.c
LUAJIT_SRC     := $(filter-out $(LUAJIT_EXCLUDE),$(wildcard $(LUAJIT_DIR)/*.c))
LUAJIT_OBJ     := $(LUAJIT_SRC:%.c=$(OBJ_DIR)/%.o)

ALL_OBJ        := $(MEDUSA_OBJ) $(NETWORK_OBJ) $(WORLD_OBJ) \
                  $(GCQ_OBJ) $(RENDER3D_OBJ) $(LUAJIT_OBJ)

# ---------------------------------------------------------------------------
# Targets
# ---------------------------------------------------------------------------

LIB_MEDUSA   := $(OUT_DIR)/libMedusa$(LIB_SUFFIX).a
LIB_NETWORK  := $(OUT_DIR)/libNetwork$(LIB_SUFFIX).a
LIB_WORLD    := $(OUT_DIR)/libWorld$(LIB_SUFFIX).a
LIB_GCQ      := $(OUT_DIR)/libGCQ$(LIB_SUFFIX).a
LIB_RENDER3D := $(OUT_DIR)/libRender3D$(LIB_SUFFIX).a
LIB_LUAJIT   := $(OUT_DIR)/liblua51$(LIB_SUFFIX).a

ALL_LIBS := $(LIB_MEDUSA) $(LIB_NETWORK) $(LIB_WORLD) \
            $(LIB_GCQ) $(LIB_RENDER3D) $(LIB_LUAJIT)

.PHONY: all clean medusa network world gcq render3d luajit info
.DEFAULT_GOAL := all

all: $(ALL_LIBS)

medusa:   $(LIB_MEDUSA)
network:  $(LIB_NETWORK)
world:    $(LIB_WORLD)
gcq:      $(LIB_GCQ)
render3d: $(LIB_RENDER3D)
luajit:   $(LIB_LUAJIT)

$(LIB_MEDUSA): $(MEDUSA_OBJ) | $(OUT_DIR)
	@echo "  AR    $@"
	@$(AR) $(ARFLAGS) $@ $^

$(LIB_NETWORK): $(NETWORK_OBJ) | $(OUT_DIR)
	@echo "  AR    $@"
	@$(AR) $(ARFLAGS) $@ $^

$(LIB_WORLD): $(WORLD_OBJ) | $(OUT_DIR)
	@echo "  AR    $@"
	@$(AR) $(ARFLAGS) $@ $^

$(LIB_GCQ): $(GCQ_OBJ) | $(OUT_DIR)
	@echo "  AR    $@"
	@$(AR) $(ARFLAGS) $@ $^

$(LIB_RENDER3D): $(RENDER3D_OBJ) | $(OUT_DIR)
	@echo "  AR    $@"
	@$(AR) $(ARFLAGS) $@ $^

$(LIB_LUAJIT): $(LUAJIT_OBJ) | $(OUT_DIR)
	@echo "  AR    $@"
	@$(AR) $(ARFLAGS) $@ $^

# LuaJIT-only flags:
#  LUA_USE_LINUX  — picks the Linux code paths (dlopen-based loadlib, POSIX
#                   time, readline, etc.).
#  USE_PLAIN_LUA  — gates out every luaJIT_* entry point in the core
#                   interpreter (ldo.c, lstate.c, ldebug.c, lfunc.c,
#                   linit.c, loadlib.c).  Without this, the core calls into
#                   luaJIT_run / luaJIT_initstate / etc., which would
#                   require the ljit_*.c codegen files we've excluded — and
#                   those need DynASM (dasm_proto.h) which isn't bundled
#                   and is x86-only anyway.
#  COCO_DISABLE   — drops LuaCoco's asm-based coroutine implementation
#                   (lcoco.c).  TODO: confirm DarkSpace scripts don't lean
#                   on coroutines yielding through C-call boundaries.  If
#                   we hit a missing-symbol link error from coco, revisit.
$(LUAJIT_OBJ): EXTRA_CFLAGS := -DLUA_USE_LINUX -DUSE_PLAIN_LUA -DCOCO_DISABLE

# Compile rules.  -MMD -MP emits header-dependency files next to each .o so
# subsequent rebuilds know to recompile when an included header changes.
# Adding Makefile as a hard prerequisite means flag edits (CXXFLAGS, EXTRA_
# CFLAGS, defines) trigger a rebuild — without this, changing -DUSE_PLAIN_
# LUA et al silently leaves stale .o files with the old flag set.
$(OBJ_DIR)/%.o: %.cpp Makefile
	@mkdir -p $(dir $@)
	@echo "  CXX   $<"
	@$(CXX) $(CXXFLAGS) $(EXTRA_CFLAGS) -MMD -MP -c -o $@ $<

$(OBJ_DIR)/%.o: %.c Makefile
	@mkdir -p $(dir $@)
	@echo "  CC    $<"
	@$(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MP -c -o $@ $<

$(OUT_DIR):
	@mkdir -p $@

clean:
	@echo "  RM    obj/ Bin/$(PLATFORM)/"
	@rm -rf obj Bin/$(PLATFORM)

# Diagnostic: print resolved variables so you can sanity-check before a build.
info:
	@echo "CONFIG       = $(CONFIG)"
	@echo "PLATFORM     = $(PLATFORM)"
	@echo "OUT_DIR      = $(OUT_DIR)"
	@echo "OBJ_DIR      = $(OBJ_DIR)"
	@echo "LIB_SUFFIX   = $(LIB_SUFFIX)"
	@echo "MEDUSA_SRC   = $(words $(MEDUSA_SRC_CPP) $(MEDUSA_SRC_C)) files"
	@echo "NETWORK_SRC  = $(words $(NETWORK_SRC)) files"
	@echo "WORLD_SRC    = $(words $(WORLD_SRC)) files"
	@echo "GCQ_SRC      = $(words $(GCQ_SRC)) files"
	@echo "RENDER3D_SRC = $(words $(RENDER3D_SRC)) files"
	@echo "LUAJIT_SRC   = $(words $(LUAJIT_SRC)) files"

# Auto-generated header dependencies (created by -MMD -MP above).  The
# `-include` swallows the "no such file" on the first build before any .d
# files exist.
-include $(ALL_OBJ:.o=.d)
